"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { doc, setDoc } from "firebase/firestore";
import { db, auth } from "@/lib/firebase";

export default function CreateCustomerPage() {
    const router = useRouter();
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    const [formData, setFormData] = useState({
        id: "cust_" + Math.random().toString(36).substr(2, 6),
        name: "",
        email: "",
        phone: "",
        company: "",
        industry: "Information Technology",
        customerType: "B2B",
        ownerId: "user_" + Math.random().toString(36).substr(2, 6), // Mock owner
        status: "Active",
        source: "Website",
        lifetimeValue: "0",
        city: "",
        state: "",
        country: "India",
        notes: "",
    });

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleCreateCustomer = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError("");

        try {
            // Because the user requested both using the `createCompanyAccount` backend AND the Firestore "customers/{customerId}" collection
            // 1. Call our API endpoint that fires createCompanyAccount (which creates Auth + 'companies' doc)
            const res = await fetch("/api/customers", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    email: formData.email,
                    companyName: formData.company,
                })
            });

            if (!res.ok) {
                const errorData = await res.json();
                throw new Error(errorData.error || "Failed to create company account");
            }

            const apiData = await res.json();
            const customerId = apiData.id; // User ID generated by createCompanyAccount

            // 2. Save the full schema explicitly into the `customers/{customerId}` collection
            // The prompt requested this exact collection path and fields.
            const customerDocData = {
                id: customerId, // Override local random ID with real Firebase Auth ID
                uId: auth.currentUser?.uid || null, // Current login uid
                name: formData.name,
                email: formData.email,
                phone: formData.phone,
                company: formData.company,
                industry: formData.industry,
                customerType: formData.customerType,
                ownerId: formData.ownerId,
                status: formData.status,
                source: formData.source,
                lifetimeValue: Number(formData.lifetimeValue),
                city: formData.city,
                state: formData.state,
                country: formData.country,
                notes: formData.notes,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
            };

            await setDoc(doc(db, "customers", customerId), customerDocData);

            // Navigate back to customers list
            router.push("/customers");

        } catch (err: any) {
            console.error(err);
            setError(err.message || "An unexpected error occurred.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="max-w-4xl mx-auto py-8">
            <div className="mb-8">
                <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Add New Customer</h1>
                <p className="mt-2 flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">
                    Create a new B2B or B2C customer record
                </p>
            </div>

            {error && (
                <div className="mb-6 rounded-lg bg-red-50 p-4 border border-red-200 dark:bg-red-500/10 dark:border-red-500/20">
                    <p className="text-sm font-medium text-red-800 dark:text-red-400">{error}</p>
                </div>
            )}

            <form onSubmit={handleCreateCustomer} className="space-y-8 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 lg:p-10 shadow-sm shadow-slate-100 dark:shadow-none">

                {/* Personal Information Setup */}
                <div>
                    <h3 className="text-lg font-medium leading-6 text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-3">Personal Details</h3>
                    <div className="mt-6 grid grid-cols-1 gap-y-6 gap-x-6 sm:grid-cols-6">
                        <div className="sm:col-span-3">
                            <label htmlFor="name" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Full Name</label>
                            <div className="mt-1">
                                <input type="text" name="name" id="name" required value={formData.name} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" />
                            </div>
                        </div>

                        <div className="sm:col-span-3">
                            <label htmlFor="email" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Email Address</label>
                            <div className="mt-1">
                                <input type="email" name="email" id="email" required value={formData.email} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" />
                            </div>
                        </div>

                        <div className="sm:col-span-3">
                            <label htmlFor="phone" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Phone Number</label>
                            <div className="mt-1">
                                <input type="text" name="phone" id="phone" value={formData.phone} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" />
                            </div>
                        </div>
                    </div>
                </div>

                {/* Company Information */}
                <div>
                    <h3 className="text-lg font-medium leading-6 text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-3">Company Information</h3>
                    <div className="mt-6 grid grid-cols-1 gap-y-6 gap-x-6 sm:grid-cols-6">
                        <div className="sm:col-span-3">
                            <label htmlFor="company" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Company Name</label>
                            <div className="mt-1">
                                <input type="text" name="company" id="company" required value={formData.company} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" />
                            </div>
                        </div>

                        <div className="sm:col-span-3">
                            <label htmlFor="industry" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Industry</label>
                            <div className="mt-1">
                                <select name="industry" id="industry" value={formData.industry} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white">
                                    <option>Information Technology</option>
                                    <option>Finance</option>
                                    <option>Healthcare</option>
                                    <option>Retail</option>
                                    <option>Manufacturing</option>
                                    <option>Other</option>
                                </select>
                            </div>
                        </div>

                        <div className="sm:col-span-3">
                            <label htmlFor="customerType" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Customer Type</label>
                            <div className="mt-1">
                                <select name="customerType" id="customerType" value={formData.customerType} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white">
                                    <option>B2B</option>
                                    <option>B2C</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Sales Information */}
                <div>
                    <h3 className="text-lg font-medium leading-6 text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-3">Status & Analytics</h3>
                    <div className="mt-6 grid grid-cols-1 gap-y-6 gap-x-6 sm:grid-cols-6">
                        <div className="sm:col-span-2">
                            <label htmlFor="status" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Status</label>
                            <div className="mt-1">
                                <select name="status" id="status" value={formData.status} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white">
                                    <option>Active</option>
                                    <option>Inactive</option>
                                    <option>Lead</option>
                                </select>
                            </div>
                        </div>

                        <div className="sm:col-span-2">
                            <label htmlFor="source" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Source</label>
                            <div className="mt-1">
                                <select name="source" id="source" value={formData.source} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white">
                                    <option>Website</option>
                                    <option>Referral</option>
                                    <option>Cold Call</option>
                                    <option>Organic Search</option>
                                </select>
                            </div>
                        </div>

                        <div className="sm:col-span-2">
                            <label htmlFor="lifetimeValue" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Lifetime Value (₹)</label>
                            <div className="mt-1">
                                <input type="number" name="lifetimeValue" id="lifetimeValue" value={formData.lifetimeValue} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" />
                            </div>
                        </div>
                    </div>
                </div>

                {/* Address & Notes */}
                <div>
                    <h3 className="text-lg font-medium leading-6 text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-3">Location & Notes</h3>
                    <div className="mt-6 grid grid-cols-1 gap-y-6 gap-x-6 sm:grid-cols-6">
                        <div className="sm:col-span-2">
                            <label htmlFor="city" className="block text-sm font-medium text-slate-700 dark:text-slate-300">City</label>
                            <div className="mt-1">
                                <input type="text" name="city" id="city" value={formData.city} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" />
                            </div>
                        </div>

                        <div className="sm:col-span-2">
                            <label htmlFor="state" className="block text-sm font-medium text-slate-700 dark:text-slate-300">State</label>
                            <div className="mt-1">
                                <input type="text" name="state" id="state" value={formData.state} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" />
                            </div>
                        </div>

                        <div className="sm:col-span-2">
                            <label htmlFor="country" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Country</label>
                            <div className="mt-1">
                                <input type="text" name="country" id="country" value={formData.country} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" />
                            </div>
                        </div>

                        <div className="sm:col-span-6">
                            <label htmlFor="notes" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Internal Notes</label>
                            <div className="mt-1">
                                <textarea name="notes" id="notes" rows={3} value={formData.notes} onChange={handleChange} className="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-3 dark:bg-slate-800 dark:border-slate-700 dark:text-white" placeholder="Interested in enterprise CRM package." />
                            </div>
                        </div>
                    </div>
                </div>

                <div className="pt-5 flex justify-end gap-3 border-t border-slate-200 dark:border-slate-800">
                    <button
                        type="button"
                        onClick={() => router.push("/customers")}
                        className="rounded-lg border border-slate-300 bg-white dark:bg-slate-800 dark:border-slate-700 px-5 py-2.5 text-sm font-medium text-slate-700 dark:text-slate-300 shadow-sm hover:bg-slate-50 dark:hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                    >
                        Cancel
                    </button>
                    <button
                        type="submit"
                        disabled={loading}
                        className="inline-flex justify-center rounded-lg border border-transparent bg-indigo-600 px-6 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {loading ? "Creating..." : "Create Customer"}
                    </button>
                </div>
            </form>
        </div>
    );
}
